### ISSUE TITLE
Build error on FreeBSD 9.1

### ISSUE THREAD

**Issue by heshamsafi** [cgdb/cgdb#71]
```
gcc -DHAVE_CONFIG_H -I. -I../..      -g -O2 -MT pseudo.o -MD -MP -MF .deps/pseudo.Tpo -c -o pseudo.o pseudo.c
pseudo.c: In function 'pty_open':
pseudo.c:332: error: 'I_PUSH' undeclared (first use in this function)
pseudo.c:332: error: (Each undeclared identifier is reported only once
pseudo.c:332: error: for each function it appears in.)
```

I think it is because pty_open assumes that my system supports STREAMS, but it doesn't.

**Comment by scottlu** [comment]
Builds ok in FreeBSD 10.3 and FreeBSD 9.1 is no longer available for download from FreeBSD website.

**Comment by mikesart** [comment]
Closing really old issues. Please open a new bug if this problem still exists. Thanks.
