### ISSUE TITLE
compile with gcc 4.8.5?

### ISSUE THREAD

**Issue by biocyberman** [cgdb/cgdb#184]
```
gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)
Copyright (C) 2015 Free Software Foundation
```

I followed these instructions:

```
$ git clone git://github.com/cgdb/cgdb.git
$ cd cgdb
$ ./autogen.sh

$ ./configure --prefix=/usr/local
$ make

```
I got this error when trying to `make` cgdb:

```
g++ -DHAVE_CONFIG_H -I. -I../..    -I../../lib/util -g -O2 -MT kui.o -MD -MP -MF .deps/kui.Tpo -c -o kui.o kui.cpp
kui.cpp: In function ‘int kui_ms_destroy(kui_map_set*)’:
kui.cpp:310:15: error: ‘it’ does not name a type
     for (auto it = kui_ms->maps.cbegin(); it != kui_ms->maps.cend();)
               ^
kui.cpp:310:43: error: expected ‘;’ before ‘it’
     for (auto it = kui_ms->maps.cbegin(); it != kui_ms->maps.cend();)
                                           ^
kui.cpp:310:43: error: ‘it’ was not declared in this scope
kui.cpp:310:62: error: ‘class std::map<std::basic_string<char>, kui_map*>’ has no member named ‘cend’
     for (auto it = kui_ms->maps.cbegin(); it != kui_ms->maps.cend();)
                                                              ^
kui.cpp: In function ‘int kui_ms_register_map(kui_map_set*, const char*, const char*)’:
kui.cpp:334:10: error: ‘iter’ does not name a type
     auto iter = kui_ms->maps.find(key_data);
          ^
kui.cpp:335:9: error: ‘iter’ was not declared in this scope
     if (iter != kui_ms->maps.end()) {
         ^
kui.cpp: In function ‘int kui_ms_deregister_map(kui_map_set*, const char*)’:
kui.cpp:353:10: error: ‘iter’ does not name a type
     auto iter = kui_ms->maps.find(key);
          ^
kui.cpp:354:9: error: ‘iter’ was not declared in this scope
     if (iter == kui_ms->maps.end()) {
         ^
kui.cpp:359:40: error: ‘iter’ was not declared in this scope
     if (kui_tree_delete(kui_ms->ktree, iter->second->literal_key) == -1)
                                        ^
kui.cpp:362:21: error: ‘iter’ was not declared in this scope
     kui_map_destroy(iter->second);
                     ^
kui.cpp: In function ‘int kui_update_buffer(kuictx*, kui_map*, int, int*)’:
kui.cpp:672:15: error: ‘it’ does not name a type
     for (auto it : kctx->volatile_buffer) {
               ^
kui.cpp:677:5: error: expected ‘;’ before ‘if’
     if (map_was_found) {
     ^
kui.cpp:677:5: error: expected primary-expression before ‘if’
kui.cpp:677:5: error: expected ‘;’ before ‘if’
kui.cpp:677:5: error: expected primary-expression before ‘if’
kui.cpp:677:5: error: expected ‘)’ before ‘if’
kui.cpp: In function ‘int kui_manager_get_terminal_keys_kui_map(kui_manager*, cgdb_key, const std::list<std::basic_string<char> >&)’:
kui.cpp:1072:22: error: ISO C++ forbids declaration of ‘data’ with no type [-fpermissive]
     for (const auto &data : keyseq) {
                      ^
kui.cpp:1072:29: error: range-based ‘for’ loops are not allowed in C++98 mode
     for (const auto &data : keyseq) {
                             ^
kui.cpp:1073:43: error: request for member ‘c_str’ in ‘data’, which is of non-class type ‘const int’
         kui_ms_register_map(map_set, data.c_str(), keycode_str);
                                           ^
make[3]: *** [kui.o] Error 1
make[3]: Leaving directory `/home/ec2-user/environment/cgdb/lib/kui'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/ec2-user/environment/cgdb/lib'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/ec2-user/environment/cgdb'
make: *** [all] Error 2

 
```

**Comment by biocyberman** [comment]
I got it to compile with this configure command:

`CXXFLAGS='-std=c++11' ./configure --prefix=/usr/local`

**Comment by idinwoodie** [comment]
@biocyberman that was the correct solution. Cgdb makes use of the added functionality of C++11 which necessitates the use of the `-std=c++11` flag for compilation.

**Comment by biocyberman** [comment]
Can that flag be put into configure.init or somewhere so that end-user does not need to set it manually?
